[package]
name = "urdf-viz"
version = "0.9.1"
authors = ["Takashi Ogura <t.ogura@gmail.com>"]
description = "URDF visualization"
license = "Apache-2.0"
keywords = ["robotics", "urdf", "visualization"]
categories = ["visualization"]
repository = "https://github.com/OTL/urdf-viz"
documentation = "http://docs.rs/urdf-viz"
readme = "README.md"
exclude = ["img/*", "ci/*"]

[features]
default = ["assimp"]

[dependencies]
alga = "0.5"
env_logger = "0.4.2"
glfw = { version = "0.15.0", default-features = false }
k = "0.10.0"
kiss3d = "0.11.0"
log = "0.3"
nalgebra = "0.13.0"
rand = "0.3.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
urdf-rs = "0.4.2"

assimp = { version = "0.3.1", optional = true }
assimp-sys = "0.3.1"

[[bin]]
name = "urdf-viz"
path = "src/urdf_viewer.rs"
